"""
ORM models for VoyageAI.

Design notes
------------
* `User` is the only identity: a UUID generated by the Streamlit client on
  first visit and stored in a browser cookie. No login, no email.
* Every "vote" or "feedback" row is scoped to a User + a `target` descriptor
  (tab name + optional content hash) so we can aggregate without needing
  separate tables per feature.
* `Message` stores chatbot turns with a JSON blob for RAG sources so we can
  render citations.
"""
from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from .database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> dt.datetime:
    return dt.datetime.utcnow()


class User(Base):
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=_uuid)
    created_at = Column(DateTime, default=_now, nullable=False)
    # Optional display name — not used in A3 but cheap to keep.
    display_name = Column(String, nullable=True)

    trips = relationship("Trip", back_populates="user", cascade="all, delete-orphan")
    messages = relationship("Message", back_populates="user", cascade="all, delete-orphan")
    votes = relationship("Vote", back_populates="user", cascade="all, delete-orphan")
    feedback = relationship("Feedback", back_populates="user", cascade="all, delete-orphan")
    itineraries = relationship("Itinerary", back_populates="user", cascade="all, delete-orphan")


class Trip(Base):
    """A trip configuration the user planned (one per 'search')."""
    __tablename__ = "trips"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=_now, nullable=False)

    origin_city = Column(String, nullable=True)
    destination_city = Column(String, nullable=False)
    depart_date = Column(String, nullable=True)  # ISO date
    return_date = Column(String, nullable=True)
    travelers = Column(Integer, nullable=True)
    budget_eur = Column(Integer, nullable=True)
    style = Column(String, nullable=True)
    interests = Column(JSON, nullable=True)  # list[str]
    food_prefs = Column(JSON, nullable=True)
    # Snapshot of full search params (fl_b, ht_b, etc) for reproducibility.
    params_snapshot = Column(JSON, nullable=True)

    user = relationship("User", back_populates="trips")
    messages = relationship("Message", back_populates="trip", cascade="all, delete-orphan")
    itineraries = relationship("Itinerary", back_populates="trip", cascade="all, delete-orphan")


class Message(Base):
    """One chatbot turn (user OR assistant)."""
    __tablename__ = "messages"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    trip_id = Column(String, ForeignKey("trips.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=_now, nullable=False)

    role = Column(String, nullable=False)  # "user" | "assistant" | "system"
    content = Column(Text, nullable=False)
    # For assistant messages: list of retrieval sources [{source, score, snippet}].
    sources = Column(JSON, nullable=True)

    user = relationship("User", back_populates="messages")
    trip = relationship("Trip", back_populates="messages")


class Vote(Base):
    """
    User validation votes — e.g. "AI-optimized itinerary vs manual planning?".

    `target_type` is a short tag like 'itinerary', 'budget', 'chat', 'packing'.
    `target_id` is optional (e.g. an itinerary id). `choice` is free-form so
    we can reuse this table for thumbs-up/down, multi-option polls, etc.
    """
    __tablename__ = "votes"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    trip_id = Column(String, ForeignKey("trips.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=_now, nullable=False)

    target_type = Column(String, nullable=False, index=True)
    target_id = Column(String, nullable=True)
    choice = Column(String, nullable=False)  # e.g. "up" / "down" / "ai" / "manual"

    user = relationship("User", back_populates="votes")


class Feedback(Base):
    """Free-text feedback tied to a suggestion ("Did this help your trip?")."""
    __tablename__ = "feedback"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    trip_id = Column(String, ForeignKey("trips.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=_now, nullable=False)

    target_type = Column(String, nullable=False, index=True)
    target_id = Column(String, nullable=True)
    helpful = Column(Integer, nullable=True)  # 1 = yes, 0 = no, null = unknown
    note = Column(Text, nullable=True)

    user = relationship("User", back_populates="feedback")


class Itinerary(Base):
    """
    A generated itinerary. We keep raw markdown (legacy A2 format) AND an
    optional structured JSON (new multi-day detailed version) so the UI can
    render either.
    """
    __tablename__ = "itineraries"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    trip_id = Column(String, ForeignKey("trips.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=_now, nullable=False)

    destination = Column(String, nullable=False)
    days = Column(Integer, nullable=True)
    markdown = Column(Text, nullable=True)
    structured = Column(JSON, nullable=True)  # {days: [{day_n, morning, afternoon, evening, ...}]}
    source = Column(String, nullable=True)  # "classic" | "agent" | "regen_day"

    user = relationship("User", back_populates="itineraries")
    trip = relationship("Trip", back_populates="itineraries")
